- name: Create the databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
  with_items: "{{ mariadb_databases }}"
  become: true
  register: _db

- name: Copy database init scripts
  copy:
    src: "{{ item.item.init_script }}"
    dest: "/tmp/{{ item.item.init_script | basename }}"
    mode: "0600"
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined

- name: Initialise databases
  mysql_db:
    name: "{{ item.item.name }}"
    state: import
    target: "/tmp/{{ item.item.init_script | basename }}"
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
  with_items: "{{ _db.results }}"
  become: true
  when:
    - item.changed
    - item.item.init_script is defined

- name: Delete init scripts from the server
  file:
    name: "/tmp/{{ item.item.init_script | basename }}"
    state: absent
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined

Summary:- this play is creating the databases,  copying scripts from _db to a specified path, running the scripts to initialize the databases and in the last deleting the scripts from the machine